In [2]:
import numpy as np

In [6]:
a1 = np.array([[1., 1.],[2., -2.],[3., 3.]])
a2 = np.array([1, 2, 3, 4])
a3 = np.array([a2[0:i].sum() for i in range(0, len(a2))])
a3.shape
print(a3)

[0 1 3 6]


In [7]:
np.split(a1, a3)

[array([], shape=(0, 2), dtype=float64),
 array([[1., 1.]]),
 array([[ 2., -2.],
        [ 3.,  3.]]),
 array([], shape=(0, 2), dtype=float64),
 array([], shape=(0, 2), dtype=float64)]

In [32]:
lst = [[[1, 2], [3, 4]], [[5, 6]]]
pad = len(max(lst, key=len))
#np.array([[i + [0]*(pad-len(i)) for i in lst]])
print(pad)
print(lst[0],lst[1])

2
[[1, 2], [3, 4]] [[5, 6]]


In [51]:
lst = [[1, 2, 3, 4], [1, 2, 0, 0]]
l = np.array_split(lst,1,axis=0)
print(l)

[array([[1, 2, 3, 4],
       [1, 2, 0, 0]])]


#### Array aus latent_representation und Anzahl der Wavesets pro Song

In [ ]:
song_orders = [latent_representation[num_of_ws_per_song[0:i].sum():num_of_ws_per_song[0:i+1].sum(), :] for i in range(0, len(num_of_ws_per_song))]
#print(song_orders[23:24])

In [62]:
for x in range(0, 9):
    globals()['string%s' % x] = 'Hello'

In [ ]:
with open("data/song_orders.txt", "wb") as fp:
    pickle.dump(latent_representation[0:i], fp)